export * from './get-current-storage-usage-repository.protocol'
export * from './save-file-storage-service.protocol'
export * from './save-file-repository.protocol'
export * from './get-files-by-album-id-repositoriy.protocol'
export * from './get-files-urls-service.protocol'
export * from './get-files-by-ids-repository.protocol'
export * from './update-file-repository.protocol'
