name: Build

on:
  workflow_call:
    inputs:
      project-folder:
        description: "Name of the project folder"
        required: true
        type: string
      run-tests:
        description: "If run tests step should be executed"
        type: boolean
        required: false
        default: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "./yarn.lock"

      - name: install dependencies
        working-directory: apps/${{ inputs.project-folder }}
        run: yarn install --immutable

      - name: build app
        working-directory: apps/${{ inputs.project-folder }}
        run: yarn build

      - name: run tests
        working-directory: apps/${{ inputs.project-folder }}
        if: ${{ inputs.run-tests }}
        run: yarn test:cov
