name: Build (File Manager)

on:
  push:
    branches: ["main"]
    paths:
      - "file-manager/**"
  pull_request:
    branches: ["main"]
    paths:
      - "file-manager/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "file-manager/package-lock.json"

      - name: install dependencies
        working-directory: file-manager
        run: npm ci

      - name: generate build
        working-directory: file-manager
        run: npm run build --if-present

      - name: run tests
        working-directory: file-manager
        run: npm test
