name: Build (File Manager)

on:
  push:
    branches: ["main"]
    paths:
      - "apps/file-manager/**"
  pull_request:
    branches: ["main"]
    paths:
      - "apps/file-manager/**"
  workflow_dispatch:

jobs:
  run-build:
    uses: ./.github/workflows/build.yml
    with:
      project-folder: "file-manager"
