name: Build (User)

on:
  push:
    branches: ["main"]
    paths:
      - "apps/user/**"
  pull_request:
    branches: ["main"]
    paths:
      - "apps/user/**"
  workflow_dispatch:

jobs:
  run-build:
    uses: ./.github/workflows/build.yml
    with:
      project-folder: "user"
