name: Build (Web App)

on:
  push:
    branches: ["main"]
    paths:
      - "web/**"
  pull_request:
    branches: ["main"]
    paths:
      - "web/**"
  workflow_dispatch:

jobs:
  run-build:
    uses: ./.github/workflows/build.yml
    with:
      project-folder: web
      run-tests: false
